
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        image_name_tag="nginx_uwsgi_nodejs:0.0.1"
        docker build . --file Dockerfile --tag $image_name_tag
    - name: Push Docker Image
      run: |
        new_image="$ALIYUN_REGISTRY/yancheng278/$image_name_tag"
        echo "docker tag $image_name_tag $new_image"
        docker tag $image_name_tag $new_image
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        docker push nginx_uwsgi_nodejs:0.0.1
